import Head from "next/head";
import { useEffect, useState } from "react";
import { API } from "../utils/axios";
import { AxiosResponse } from "axios";
import { QueryFunction, useQuery } from "@tanstack/react-query";

interface SWPeoples {
  count: number;
  next: string;
  prev: string;
  results: People[];
}

interface People {
  name: string;
  starships: string[];
}

interface Starship {
  name: string;
  manufacturer: string;
}

export default function FirstPost() {
  // const [people, setPeople] = useState<People[]>([]);
  const [loading, setLoading] = useState(false);
  const [starshipLoading, setStarshipLoading] = useState(false);
  const [starships, setStarships] = useState<Starship[]>([]);

  // const fetchPeople = async () => {
  //   try {
  //     setLoading(true);
  //     const allpeople: AxiosResponse<SWPeople> = await API.get("people/");
  //     setPeople(allpeople.data.results);
  //     console.log(allpeople.data.results);
  //   } catch (e) {
  //     console.log(e);
  //   } finally {
  //     setLoading(false);
  //   }
  // };

  const fetchPeople: QueryFunction<{ data: SWPeoples }> = async () => {
    const { data } = await API.get("people/");
    return { data };
  };

  const {
    data: people,
    isLoading,
    refetch: refetchPeople,
  } = useQuery(["allPeople"], fetchPeople, {
    cacheTime: 100,
    staleTime: 10,
    enabled: true,
    onError: (err) => {
      console.log(err);
    },
    onSuccess: (data) => {
      console.log("asd");
    },
    // select: (data: SWPeoples) => {
    //   return data.results[0].name
    // }
  });

  const fetchAllStarship = async (ids: string[]) => {
    setStarshipLoading(true);
    const promisesArr = ids.map(
      async (idx) => await API.get(`starships/${idx}`)
    );
    Promise.all(promisesArr)
      .then((allStarshipsArr: AxiosResponse<Starship>[]) => {
        const cleanStarships = allStarshipsArr.map((a) => {
          const returnObj = {
            name: a.data.name,
            manufacturer: a.data.manufacturer,
          };
          return returnObj;
        });
        setStarships(cleanStarships);
      })
      .catch((e) => console.log(e));
    setStarshipLoading(false);
  };

  useEffect(() => {
    fetchPeople();
  }, []);

  const getIdFromURL = (url: string) => {
    const splittedArray = url?.split("/");
    return splittedArray?.[splittedArray?.length - 2];
  };

  const handlePeopleClick = (attr: People) => {
    setStarships([]);
    const ids = attr.starships.map((eachUrl) => {
      return getIdFromURL(eachUrl);
      // fetch each starship using the id
    });
    fetchAllStarship(ids);
  };

  return (
    <>
      <Head>
        <title>Sandip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Available Peoples:</h2>
        <br />
        {isLoading
          ? "loading...."
          : people?.data?.results?.map((people, index) => {
              return (
                <div key={index}>
                  <button onClick={() => {}}>{people.name}</button>
                </div>
              );
            })}
      </div>
      <div>
        <h2>current starships:</h2>
        <br />
        {loading
          ? "loading...."
          : starships?.map((starship) => {
              return (
                <div>
                  <button onClick={() => {}}>{starship.name}</button>
                </div>
              );
            })}
      </div>
    </>
  );
}
